### ISSUE TITLE
Invalid parameter: 'target' on Archive[kibana-4.3.1-linux-x64]

### ISSUE THREAD

**Issue by erikanderson** [lesaux/puppet-kibana4#46] opened 2016-01-25 18:12 UTC
From time to time I get this error when running puppet on my kibana4 node:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: 
Invalid parameter: 'target' on Archive[kibana-4.3.1-linux-x64] 
at .../modules/kibana4/manifests/install.pp:41 on node ****
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

Doesn't happen every time though which is weird

**Comment by alex-harvey-z3q** [comment] 2016-01-26 13:58
I would say that it's unlikely to be this module at fault.  Target is a valid parameter for the camptocamp/archive module that it's calling.  I suspect something is changing on your system from time to time that you're unaware of?

**Comment by erikanderson** [comment] 2016-01-28 18:02
I imagine you are right, I will do some digging

**Comment by lesaux** [comment] 2016-03-07 02:47
I will close this. Please re-open if you think the issue is with the module.

**Closed as completed by lesaux** 2016-03-07 02:47 UTC

**Comment by m0numentum** [comment] 2016-05-09 12:31
Hello everyone !

I'm issuing the same issue for Kibana 4.4. Even if I force the target parameter to something like '/opt', Puppet does not compile the catalog.

@erikanderson, did you find what was wrong ?

Thanks a lot for your time.
